<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;

class UserWalletLog extends Model
{
    //

    protected $primaryKey = 'id';
    protected $table = 'user_wallet_logs';
    protected $guarded = [];

    protected $appends = ['log_type_text', 'coin_name'];

    protected $casts = [
        'before_balance' => 'real',
        'after_balance' => 'real',
        'amount' => 'real',
    ];

//    protected $dateFormat = 'U';

    public static $logType_ = [
        'store_otc_sell_entrust' => "发布OTC出售广告委托",
        'cancelOtcEntrust' => "撤销OTC委托",
        'confirmOtcOrder' => "OTC订单交易完成",
        'store_otc_order' => "我要出售",
        'cancel_otc_order' => "订单关闭",
        'register_send_stai' => "注册赠送",
        'register_invitation' => "注册邀请奖励",
        'admin_recharge' => "后台充值",
        'recharge' => "コインチャージ",
        'recharge_audit' => "コインチャージ審査です",
        'withdraw' => "コインを引き上げます",
        'cancel_withdraw' => "通貨引き上げ撤回です",
        'withdraw_fee' => "コイン引き出し手数料",
        'reject_withdraw' => "通貨引上げ審査拒否です",
        'fund_transfer' => "資金を回す",
        "bet_option" => "買い入れオプション",
        "bet_option_fee" => "オプション手数料",
        "option_order_delivery" => "オプション受渡し",
        "option_order_cancel" => "オプション註文流局です",
        "store_buy_entrust" => "コイン取引の購入依頼を行います",
        "store_sell_entrust" => "コイン取引の販売依頼を出します",
        "entrust_exchange" => "コインの取引が成立しました",
        "cancel_entrust" => "請求を取り下げます",
        "dividend" => "配当します",
        "subscribe" => "申し込みます",
        "subscribe_activity" => "申し込みキャンペーン贈呈です",
        "open_position" => "先物取引凍結です",
        "open_position_fee" => "先物オープン手数料です",
        "contract_deal" => "先物取引です",
        "close_position" => "先物取引証拠金の放出です",
        "close_position_fee" => "先物取引手数料です",
        "close_long_position" => "先物平価損益計算書",
        "close_short_position" => "先物取引損益計算書",
        "system_flat_position" => "システム強平化です",
        "system_close_position" => "パンク保証金放出です",
        "system_close_position_fee" => "パンク手数料です",
        "system_close_long_position" => "爆倉平多損益決算です",
        "system_close_short_position" => "損益計算書の提出が滞りました",
        "cancel_open_position" => "契約破棄、保証金返還です",
        "cancel_open_position_fee" => "契約破棄,手数料返金です",
        "position_capital_cost" => "先物取引資金料です",
        "buy_pledge_product" => "マイニングの質を買います",
        "sell_pledge_product" => "ロック解除マイニングです",
        "sign_send_stai" => 'サインイン贈呈', // 小白
    ];

    public static $logType = [
        'zh-CN' => [
            'store_otc_sell_entrust' => "发布OTC出售广告委托",
            'cancelOtcEntrust' => "撤销OTC委托",
            'confirmOtcOrder' => "OTC订单交易完成",
            'store_otc_order' => "我要出售",
            'cancel_otc_order' => "订单关闭",
            'register_send_stai' => "注册赠送",
            'register_invitation' => "注册邀请奖励",
            'admin_recharge' => "系统操作",
            'recharge' => "币种充值",
            'recharge_audit' => "币种充值审核",
            'withdraw' => "提交提现",
            'cancel_withdraw' => "取消提现",
            'withdraw_fee' => "提现手续费",
            'reject_withdraw' => "驳回提现",
            'fund_transfer' => "资金划转",
            "bet_option" => "合约买入",
            "bet_option_fee" => "手续费",
            "option_order_delivery" => "オプション受渡し",
            "option_order_cancel" => "オプション註文流局です",
            "store_buy_entrust" => "买单委托",
            "store_sell_entrust" => "卖单委托",
            "entrust_exchange" => "委托成交",
            "cancel_entrust" => "撤销委托",
            "dividend" => "配当します",
            "subscribe" => "申し込みます",
            "subscribe_activity" => "申し込みキャンペーン贈呈です",
            "open_position" => "开仓",
            "open_position_fee" => "开仓手续费",
            "contract_deal" => "合约成交",
            "close_position" => "平仓返回保证金",
            "close_position_fee" => "平仓手续费",
            "close_long_position" => "平多收益",
            "close_short_position" => "平空收益",
            "system_flat_position" => "系统强平",
            "system_close_position" => "爆仓保证金",
            "system_close_position_fee" => "爆仓手续费",
            "system_close_long_position" => "爆仓平多收益",
            "system_close_short_position" => "爆仓平空收益",
            "cancel_open_position" => "撤销返回保证金",
            "cancel_open_position_fee" => "撤销返回手续费",
            "position_capital_cost" => "合约交易手续费",
            "buy_pledge_product" => "マイニングの質を買います",
            "sell_pledge_product" => "ロック解除マイニングです",
            "sign_send_stai" => 'サインイン贈呈', // 小白
            'time_place' => '合约买入',
            'time_cancel' => '取消合约',
            'time_order_close' => '合约卖出'
        ],
        //英语
        'en' => [ //英语
            'store_otc_sell_entrust' => "Publish OTC sell advertisement entrust",
            'cancelOtcEntrust' => "Cancel OTC entrust",
            'confirmOtcOrder' => "OTC order transaction completed",
            'store_otc_order' => "I want to sell",
            'cancel_otc_order' => "Order closed",
            'register_send_stai' => "Register gift",
            'register_invitation' => "Register invitation reward",
            'admin_recharge' => "System operation",
            'recharge' => "Currency recharge",
            'recharge_audit' => "Currency recharge audit",
            'withdraw' => "Submit withdrawal",
            'cancel_withdraw' => "Cancel withdrawal",
            'withdraw_fee' => "Withdrawal fee",
            'reject_withdraw' => "Reject withdrawal",
            'fund_transfer' => "Fund transfer",
            'bet_option' => "Contract buy",
            'bet_option_fee' => "Handling fee",
            'option_order_delivery' => "Option delivery",
            'option_order_cancel' => "Option order canceled",
            'store_buy_entrust' => "Buy order entrust",
            'store_sell_entrust' => "Sell order entrust",
            'entrust_exchange' => "Entrust transaction",
            'cancel_entrust' => "Cancel entrust",
            'dividend' => "Distribute dividends",
            'subscribe' => "Subscribe",
            'subscribe_activity' => "Subscription campaign gift",
            'open_position' => "Open position",
            'open_position_fee' => "Open position fee",
            'contract_deal' => "Contract transaction",
            'close_position' => "Close position and return margin",
            'close_position_fee' => "Close position fee",
            'close_long_position' => "Close long position profit",
            'close_short_position' => "Close short position profit",
            'system_flat_position' => "System forced liquidation",
            'system_close_position' => "Liquidation margin",
            'system_close_position_fee' => "Liquidation fee",
            'system_close_long_position' => "Liquidation long position profit",
            'system_close_short_position' => "Liquidation short position profit",
            'cancel_open_position' => "Cancel and return margin",
            'cancel_open_position_fee' => "Cancel and return fee",
            'position_capital_cost' => "Contract trading fee",
            'buy_pledge_product' => "Buy mining pledge",
            'sell_pledge_product' => "Unlock mining",
            'sign_send_stai' => "Sign-in gift",
            'time_place' => "Contract buy",
            'time_cancel' => "Cancel contract",
            'time_order_close' => "Contract sell",
        ],
        //西班牙语
        'spa' => [
            'store_otc_sell_entrust' => "Publicar anuncio de venta OTC confiado",
            'cancelOtcEntrust' => "Cancelar encargo OTC",
            'confirmOtcOrder' => "Transacción de orden OTC completada",
            'store_otc_order' => "Quiero vender",
            'cancel_otc_order' => "Orden cerrada",
            'register_send_stai' => "Regalo de registro",
            'register_invitation' => "Recompensa por invitación de registro",
            'admin_recharge' => "Operación del sistema",
            'recharge' => "Recarga de moneda",
            'recharge_audit' => "Auditoría de recarga de moneda",
            'withdraw' => "Enviar solicitud de retiro",
            'cancel_withdraw' => "Cancelar retiro",
            'withdraw_fee' => "Comisión de retiro",
            'reject_withdraw' => "Rechazar retiro",
            'fund_transfer' => "Transferencia de fondos",
            'bet_option' => "Compra de contrato",
            'bet_option_fee' => "Comisión de manejo",
            'option_order_delivery' => "Entrega de opción",
            'option_order_cancel' => "Orden de opción cancelada",
            'store_buy_entrust' => "Encargo de orden de compra",
            'store_sell_entrust' => "Encargo de orden de venta",
            'entrust_exchange' => "Transacción confiada",
            'cancel_entrust' => "Cancelar encargo",
            'dividend' => "Distribuir dividendos",
            'subscribe' => "Suscribirse",
            'subscribe_activity' => "Regalo de campaña de suscripción",
            'open_position' => "Abrir posición",
            'open_position_fee' => "Comisión de apertura de posición",
            'contract_deal' => "Transacción de contrato",
            'close_position' => "Cerrar posición y devolver margen",
            'close_position_fee' => "Comisión de cierre de posición",
            'close_long_position' => "Cerrar posición larga con ganancia",
            'close_short_position' => "Cerrar posición corta con ganancia",
            'system_flat_position' => "Liquidación forzada del sistema",
            'system_close_position' => "Margen de liquidación",
            'system_close_position_fee' => "Comisión de liquidación",
            'system_close_long_position' => "Ganancia de liquidación de posición larga",
            'system_close_short_position' => "Ganancia de liquidación de posición corta",
            'cancel_open_position' => "Cancelar y devolver margen",
            'cancel_open_position_fee' => "Cancelar y devolver comisión",
            'position_capital_cost' => "Comisión de trading de contrato",
            'buy_pledge_product' => "Comprar prenda de minería",
            'sell_pledge_product' => "Desbloquear minería",
            'sign_send_stai' => "Regalo de inicio de sesión",
            'time_place' => "Compra de contrato",
            'time_cancel' => "Cancelar contrato",
            'time_order_close' => "Venta de contrato",
        ],
        //法语
        'fra' => [
            'store_otc_sell_entrust' => "Publier une annonce de vente OTC confiée",
            'cancelOtcEntrust' => "Annuler l'ordre OTC",
            'confirmOtcOrder' => "Transaction d'ordre OTC terminée",
            'store_otc_order' => "Je veux vendre",
            'cancel_otc_order' => "Commande fermée",
            'register_send_stai' => "Cadeau d'inscription",
            'register_invitation' => "Récompense d'invitation à l'inscription",
            'admin_recharge' => "Fonctionnement du système",
            'recharge' => "Recharge de devise",
            'recharge_audit' => "Audit de recharge de devise",
            'withdraw' => "Soumettre un retrait",
            'cancel_withdraw' => "Annuler le retrait",
            'withdraw_fee' => "Frais de retrait",
            'reject_withdraw' => "Rejeter le retrait",
            'fund_transfer' => "Transfert de fonds",
            'bet_option' => "Achat de contrat",
            'bet_option_fee' => "Frais de gestion",
            'option_order_delivery' => "Livraison d'option",
            'option_order_cancel' => "Commande d'option annulée",
            'store_buy_entrust' => "Ordre d'achat confié",
            'store_sell_entrust' => "Ordre de vente confié",
            'entrust_exchange' => "Transaction confiée",
            'cancel_entrust' => "Annuler l'ordre confié",
            'dividend' => "Distribuer des dividendes",
            'subscribe' => "S'abonner",
            'subscribe_activity' => "Cadeau de campagne d'abonnement",
            'open_position' => "Ouvrir une position",
            'open_position_fee' => "Frais d'ouverture de position",
            'contract_deal' => "Transaction de contrat",
            'close_position' => "Fermer la position et retourner la marge",
            'close_position_fee' => "Frais de fermeture de position",
            'close_long_position' => "Fermer la position longue avec profit",
            'close_short_position' => "Fermer la position courte avec profit",
            'system_flat_position' => "Liquidation forcée du système",
            'system_close_position' => "Marge de liquidation",
            'system_close_position_fee' => "Frais de liquidation",
            'system_close_long_position' => "Profit de liquidation de position longue",
            'system_close_short_position' => "Profit de liquidation de position courte",
            'cancel_open_position' => "Annuler et retourner la marge",
            'cancel_open_position_fee' => "Annuler et retourner les frais",
            'position_capital_cost' => "Frais de trading de contrat",
            'buy_pledge_product' => "Acheter une garantie de minage",
            'sell_pledge_product' => "Débloquer le minage",
            'sign_send_stai' => "Cadeau de connexion",
            'time_place' => "Achat de contrat",
            'time_cancel' => "Annuler le contrat",
            'time_order_close' => "Vente de contrat",
        ],
        //德语
        'de' => [
            'store_otc_sell_entrust' => "OTC-Verkaufsanzeige veröffentlichen",
            'cancelOtcEntrust' => "OTC-Auftrag stornieren",
            'confirmOtcOrder' => "OTC-Auftragstransaktion abgeschlossen",
            'store_otc_order' => "Ich möchte verkaufen",
            'cancel_otc_order' => "Auftrag geschlossen",
            'register_send_stai' => "Registrierungsgeschenk",
            'register_invitation' => "Einladungsbelohnung für Registrierung",
            'admin_recharge' => "Systembetrieb",
            'recharge' => "Währungsaufladung",
            'recharge_audit' => "Prüfung der Währungsaufladung",
            'withdraw' => "Auszahlung einreichen",
            'cancel_withdraw' => "Auszahlung stornieren",
            'withdraw_fee' => "Auszahlungsgebühr",
            'reject_withdraw' => "Auszahlung ablehnen",
            'fund_transfer' => "Geldtransfer",
            'bet_option' => "Kontraktkauf",
            'bet_option_fee' => "Bearbeitungsgebühr",
            'option_order_delivery' => "Optionslieferung",
            'option_order_cancel' => "Optionsauftrag storniert",
            'store_buy_entrust' => "Kaufauftrag",
            'store_sell_entrust' => "Verkaufsauftrag",
            'entrust_exchange' => "Beauftragte Transaktion",
            'cancel_entrust' => "Auftrag stornieren",
            'dividend' => "Dividenden ausschütten",
            'subscribe' => "Abonnieren",
            'subscribe_activity' => "Geschenk der Abonnementkampagne",
            'open_position' => "Position eröffnen",
            'open_position_fee' => "Gebühr für Positionsöffnung",
            'contract_deal' => "Kontrakttransaktion",
            'close_position' => "Position schließen und Margin zurückgeben",
            'close_position_fee' => "Gebühr für Positionsschließung",
            'close_long_position' => "Long-Position schließen Gewinn",
            'close_short_position' => "Short-Position schließen Gewinn",
            'system_flat_position' => "Systemzwangsliquidation",
            'system_close_position' => "Liquidationsmargin",
            'system_close_position_fee' => "Liquidationsgebühr",
            'system_close_long_position' => "Liquidationsgewinn Long-Position",
            'system_close_short_position' => "Liquidationsgewinn Short-Position",
            'cancel_open_position' => "Stornieren und Margin zurückgeben",
            'cancel_open_position_fee' => "Stornieren und Gebühr zurückgeben",
            'position_capital_cost' => "Kontrakt-Handelsgebühr",
            'buy_pledge_product' => "Mining-Pfand kaufen",
            'sell_pledge_product' => "Mining freischalten",
            'sign_send_stai' => "Anmeldegeschenk",
            'time_place' => "Kontraktkauf",
            'time_cancel' => "Kontrakt stornieren",
            'time_order_close' => "Kontraktverkauf",
        ],
        //意大利语
        'it' => [
            'store_otc_sell_entrust' => "Pubblica un annuncio di vendita OTC affidato",
            'cancelOtcEntrust' => "Annulla l'ordine OTC",
            'confirmOtcOrder' => "Transazione ordine OTC completata",
            'store_otc_order' => "Voglio vendere",
            'cancel_otc_order' => "Ordine chiuso",
            'register_send_stai' => "Regalo di registrazione",
            'register_invitation' => "Premio per invito alla registrazione",
            'admin_recharge' => "Operazioni del sistema",
            'recharge' => "Ricarica valuta",
            'recharge_audit' => "Verifica ricarica valuta",
            'withdraw' => "Invia prelievo",
            'cancel_withdraw' => "Annulla prelievo",
            'withdraw_fee' => "Commissione di prelievo",
            'reject_withdraw' => "Rifiuta prelievo",
            'fund_transfer' => "Trasferimento di fondi",
            'bet_option' => "Acquisto contratto",
            'bet_option_fee' => "Commissione di gestione",
            'option_order_delivery' => "Consegna opzione",
            'option_order_cancel' => "Ordine opzione annullato",
            'store_buy_entrust' => "Ordine di acquisto affidato",
            'store_sell_entrust' => "Ordine di vendita affidato",
            'entrust_exchange' => "Transazione affidata",
            'cancel_entrust' => "Annulla ordine affidato",
            'dividend' => "Distribuire dividendi",
            'subscribe' => "Sottoscrivere",
            'subscribe_activity' => "Regalo campagna di sottoscrizione",
            'open_position' => "Aprire posizione",
            'open_position_fee' => "Commissione di apertura posizione",
            'contract_deal' => "Transazione contratto",
            'close_position' => "Chiudere posizione e restituire margine",
            'close_position_fee' => "Commissione di chiusura posizione",
            'close_long_position' => "Chiudere posizione lunga con profitto",
            'close_short_position' => "Chiudere posizione corta con profitto",
            'system_flat_position' => "Liquidazione forzata del sistema",
            'system_close_position' => "Margine di liquidazione",
            'system_close_position_fee' => "Commissione di liquidazione",
            'system_close_long_position' => "Profitto di liquidazione posizione lunga",
            'system_close_short_position' => "Profitto di liquidazione posizione corta",
            'cancel_open_position' => "Annulla e restituisci margine",
            'cancel_open_position_fee' => "Annulla e restituisci commissione",
            'position_capital_cost' => "Commissione di trading contratto",
            'buy_pledge_product' => "Acquista pegno di mining",
            'sell_pledge_product' => "Sblocca mining",
            'sign_send_stai' => "Regalo di accesso",
            'time_place' => "Acquisto contratto",
            'time_cancel' => "Annulla contratto",
            'time_order_close' => "Vendita contratto",
        ],
        //阿拉伯语
        'ar' => [
            'store_otc_sell_entrust' => "نشر إعلان بيع OTC موكل",
            'cancelOtcEntrust' => "إلغاء تكليف OTC",
            'confirmOtcOrder' => "اكتمال معاملة طلب OTC",
            'store_otc_order' => "أريد البيع",
            'cancel_otc_order' => "إغلاق الطلب",
            'register_send_stai' => "هدية التسجيل",
            'register_invitation' => "مكافأة دعوة التسجيل",
            'admin_recharge' => "نظام التشغيل",
            'recharge' => "إعادة شحن العملة",
            'recharge_audit' => "تدقيق إعادة شحن العملة",
            'withdraw' => "تقديم السحب",
            'cancel_withdraw' => "إلغاء السحب",
            'withdraw_fee' => "رسوم السحب",
            'reject_withdraw' => "رفض السحب",
            'fund_transfer' => "تحويل الأموال",
            'bet_option' => "شراء العقد",
            'bet_option_fee' => "رسوم المناولة",
            'option_order_delivery' => "تسليم الخيار",
            'option_order_cancel' => "إلغاء طلب الخيار",
            'store_buy_entrust' => "تكليف طلب الشراء",
            'store_sell_entrust' => "تكليف طلب البيع",
            'entrust_exchange' => "معاملة موكلة",
            'cancel_entrust' => "إلغاء التكليف",
            'dividend' => "توزيع الأرباح",
            'subscribe' => "الاشتراك",
            'subscribe_activity' => "هدية حملة الاشتراك",
            'open_position' => "فتح مركز",
            'open_position_fee' => "رسوم فتح المركز",
            'contract_deal' => "معاملة العقد",
            'close_position' => "إغلاق المركز وإعادة الهامش",
            'close_position_fee' => "رسوم إغلاق المركز",
            'close_long_position' => "إغلاق المركز الطويل بربح",
            'close_short_position' => "إغلاق المركز القصير بربح",
            'system_flat_position' => "تصفية قسرية للنظام",
            'system_close_position' => "هامش التصفية",
            'system_close_position_fee' => "رسوم التصفية",
            'system_close_long_position' => "ربح تصفية المركز الطويل",
            'system_close_short_position' => "ربح تصفية المركز القصير",
            'cancel_open_position' => "إلغاء وإعادة الهامش",
            'cancel_open_position_fee' => "إلغاء وإعادة الرسوم",
            'position_capital_cost' => "رسوم تداول العقد",
            'buy_pledge_product' => "شراء رهن التعدين",
            'sell_pledge_product' => "فتح التعدين",
            'sign_send_stai' => "هدية تسجيل الدخول",
            'time_place' => "شراء العقد",
            'time_cancel' => "إلغاء العقد",
            'time_order_close' => "بيع العقد",
        ],
        //荷兰语
        'nl' => [
            'store_otc_sell_entrust' => "OTC-verkoopadvertentie plaatsen",
            'cancelOtcEntrust' => "OTC-opdracht annuleren",
            'confirmOtcOrder' => "OTC-ordertransactie voltooid",
            'store_otc_order' => "Ik wil verkopen",
            'cancel_otc_order' => "Order gesloten",
            'register_send_stai' => "Registratiegeschenk",
            'register_invitation' => "Uitnodigingsbeloning voor registratie",
            'admin_recharge' => "Systeembewerking",
            'recharge' => "Valuta opladen",
            'recharge_audit' => "Controle valuta opladen",
            'withdraw' => "Opname indienen",
            'cancel_withdraw' => "Opname annuleren",
            'withdraw_fee' => "Opnamekosten",
            'reject_withdraw' => "Opname afwijzen",
            'fund_transfer' => "Geldoverdracht",
            'bet_option' => "Contract kopen",
            'bet_option_fee' => "Afhandelingskosten",
            'option_order_delivery' => "Optielevering",
            'option_order_cancel' => "Optieorder geannuleerd",
            'store_buy_entrust' => "Kooporder opdracht",
            'store_sell_entrust' => "Verkooporder opdracht",
            'entrust_exchange' => "Toevertrouwde transactie",
            'cancel_entrust' => "Opdracht annuleren",
            'dividend' => "Dividenden uitkeren",
            'subscribe' => "Abonneren",
            'subscribe_activity' => "Geschenk abonnementscampagne",
            'open_position' => "Positie openen",
            'open_position_fee' => "Kosten voor het openen van een positie",
            'contract_deal' => "Contracttransactie",
            'close_position' => "Positie sluiten en marge teruggeven",
            'close_position_fee' => "Kosten voor het sluiten van een positie",
            'close_long_position' => "Lange positie sluiten met winst",
            'close_short_position' => "Korte positie sluiten met winst",
            'system_flat_position' => "Gedwongen liquidatie door het systeem",
            'system_close_position' => "Liquidatiemarge",
            'system_close_position_fee' => "Liquidatiekosten",
            'system_close_long_position' => "Winst liquidatie lange positie",
            'system_close_short_position' => "Winst liquidatie korte positie",
            'cancel_open_position' => "Annuleren en marge teruggeven",
            'cancel_open_position_fee' => "Annuleren en kosten teruggeven",
            'position_capital_cost' => "Kosten voor contracthandel",
            'buy_pledge_product' => "Mijnbouwbelofte kopen",
            'sell_pledge_product' => "Mijnbouw ontgrendelen",
            'sign_send_stai' => "Inloggeschenk",
            'time_place' => "Contract kopen",
            'time_cancel' => "Contract annuleren",
            'time_order_close' => "Contract verkopen",
        ],
        //波兰语
        'pl' => [
            'store_otc_sell_entrust' => "Opublikuj zlecenie reklamy sprzedaży OTC",
            'cancelOtcEntrust' => "Anuluj zlecenie OTC",
            'confirmOtcOrder' => "Transakcja zlecenia OTC zakończona",
            'store_otc_order' => "Chcę sprzedać",
            'cancel_otc_order' => "Zamówienie zamknięte",
            'register_send_stai' => "Prezent za rejestrację",
            'register_invitation' => "Nagroda za zaproszenie do rejestracji",
            'admin_recharge' => "Operacja systemu",
            'recharge' => "Doładowanie waluty",
            'recharge_audit' => "Audyt doładowania waluty",
            'withdraw' => "Złóż wniosek o wypłatę",
            'cancel_withdraw' => "Anuluj wypłatę",
            'withdraw_fee' => "Opłata za wypłatę",
            'reject_withdraw' => "Odrzuć wypłatę",
            'fund_transfer' => "Transfer środków",
            'bet_option' => "Kupno kontraktu",
            'bet_option_fee' => "Opłata manipulacyjna",
            'option_order_delivery' => "Dostawa opcji",
            'option_order_cancel' => "Zlecenie opcji anulowane",
            'store_buy_entrust' => "Zlecenie kupna",
            'store_sell_entrust' => "Zlecenie sprzedaży",
            'entrust_exchange' => "Transakcja zlecona",
            'cancel_entrust' => "Anuluj zlecenie",
            'dividend' => "Wypłata dywidend",
            'subscribe' => "Subskrybuj",
            'subscribe_activity' => "Prezent kampanii subskrypcyjnej",
            'open_position' => "Otwórz pozycję",
            'open_position_fee' => "Opłata za otwarcie pozycji",
            'contract_deal' => "Transakcja kontraktu",
            'close_position' => "Zamknij pozycję i zwróć marżę",
            'close_position_fee' => "Opłata za zamknięcie pozycji",
            'close_long_position' => "Zamknij pozycję długą z zyskiem",
            'close_short_position' => "Zamknij pozycję krótką z zyskiem",
            'system_flat_position' => "Wymuszone zamknięcie systemu",
            'system_close_position' => "Marża likwidacyjna",
            'system_close_position_fee' => "Op vídeofata likwidacyjna",
            'system_close_long_position' => "Zysk likwidacji pozycji długiej",
            'system_close_short_position' => "Zysk likwidacji pozycji krótkiej",
            'cancel_open_position' => "Anuluj i zwróć marżę",
            'cancel_open_position_fee' => "Anuluj i zwróć opłatę",
            'position_capital_cost' => "Opłata za handel kontraktami",
            'buy_pledge_product' => "Kup zastaw górniczy",
            'sell_pledge_product' => "Odblokuj górnictwo",
            'sign_send_stai' => "Prezent za logowanie",
            'time_place' => "Kupno kontraktu",
            'time_cancel' => "Anuluj kontrakt",
            'time_order_close' => "Sprzedaż kontraktu",
        ],
        //葡萄牙
        'pt' => [
            'store_otc_sell_entrust' => "Publicar delegação de anúncio de venda OTC",
            'cancelOtcEntrust' => "Cancelar delegação OTC",
            'confirmOtcOrder' => "Conclusão da transação de ordem OTC",
            'store_otc_order' => "Quero vender",
            'cancel_otc_order' => "Ordem fechada",
            'register_send_stai' => "Presente de registro",
            'register_invitation' => "Recompensa por convite de registro",
            'admin_recharge' => "Operação do sistema",
            'recharge' => "Recarga de moeda",
            'recharge_audit' => "Auditoria de recarga de moeda",
            'withdraw' => "Enviar retirada",
            'cancel_withdraw' => "Cancelar retirada",
            'withdraw_fee' => "Taxa de retirada",
            'reject_withdraw' => "Rejeitar retirada",
            'fund_transfer' => "Transferência de fundos",
            'bet_option' => "Compra de contrato",
            'bet_option_fee' => "Taxa de serviço",
            'option_order_delivery' => "Entrega de opção",
            'option_order_cancel' => "Cancelamento de ordem de opção",
            'store_buy_entrust' => "Delegação de compra",
            'store_sell_entrust' => "Delegação de venda",
            'entrust_exchange' => "Transação de delegação",
            'cancel_entrust' => "Cancelar delegação",
            'dividend' => "Distribuição de dividendos",
            'subscribe' => "Assinatura",
            'subscribe_activity' => "Presente de atividade de assinatura",
            'open_position' => "Abrir posição",
            'open_position_fee' => "Taxa de abertura de posição",
            'contract_deal' => "Transação de contrato",
            'close_position' => "Fechar posição e devolver margem",
            'close_position_fee' => "Taxa de fechamento de posição",
            'close_long_position' => "Lucro de fechamento de posição comprada",
            'close_short_position' => "Lucro de fechamento de posição vendida",
            'system_flat_position' => "Liquidação forçada pelo sistema",
            'system_close_position' => "Margem de liquidação forçada",
            'system_close_position_fee' => "Taxa de liquidação forçada",
            'system_close_long_position' => "Lucro de liquidação forçada de posição comprada",
            'system_close_short_position' => "Lucro de liquidação forçada de posição vendida",
            'cancel_open_position' => "Cancelamento com devolução de margem",
            'cancel_open_position_fee' => "Taxa de devolução por cancelamento",
            'position_capital_cost' => "Taxa de transação de contrato",
            'buy_pledge_product' => "Comprar mineração com garantia",
            'sell_pledge_product' => "Desbloquear mineração",
            'sign_send_stai' => "Presente de check-in",
            'time_place' => "Compra de contrato",
            'time_cancel' => "Cancelar contrato",
            'time_order_close' => "Venda de contrato",
        ],
        //中文繁体
        'zh-TW' => [
            'store_otc_sell_entrust' => "發布OTC出售廣告委託",
            'cancelOtcEntrust' => "撤銷OTC委託",
            'confirmOtcOrder' => "OTC訂單交易完成",
            'store_otc_order' => "我要出售",
            'cancel_otc_order' => "訂單關閉",
            'register_send_stai' => "註冊贈送",
            'register_invitation' => "註冊邀請獎勵",
            'admin_recharge' => "系統操作",
            'recharge' => "幣種充值",
            'recharge_audit' => "幣種充值審核",
            'withdraw' => "提交提現",
            'cancel_withdraw' => "取消提現",
            'withdraw_fee' => "提現手續費",
            'reject_withdraw' => "駁回提現",
            'fund_transfer' => "資金劃轉",
            'bet_option' => "合約買入",
            'bet_option_fee' => "手續費",
            'option_order_delivery' => "期權交割",
            'option_order_cancel' => "期權訂單取消",
            'store_buy_entrust' => "買單委託",
            'store_sell_entrust' => "賣單委託",
            'entrust_exchange' => "委託成交",
            'cancel_entrust' => "撤銷委託",
            'dividend' => "分配股息",
            'subscribe' => "訂閱",
            'subscribe_activity' => "訂閱活動贈送",
            'open_position' => "開倉",
            'open_position_fee' => "開倉手續費",
            'contract_deal' => "合約成交",
            'close_position' => "平倉返回保證金",
            'close_position_fee' => "平倉手續費",
            'close_long_position' => "平多收益",
            'close_short_position' => "平空收益",
            'system_flat_position' => "系統強平",
            'system_close_position' => "爆倉保證金",
            'system_close_position_fee' => "爆倉手續費",
            'system_close_long_position' => "爆倉平多收益",
            'system_close_short_position' => "爆倉平空收益",
            'cancel_open_position' => "撤銷返回保證金",
            'cancel_open_position_fee' => "撤銷返回手續費",
            'position_capital_cost' => "合約交易手續費",
            'buy_pledge_product' => "購買挖礦質押",
            'sell_pledge_product' => "解鎖挖礦",
            'sign_send_stai' => "簽到贈送",
            'time_place' => "合約買入",
            'time_cancel' => "取消合約",
            'time_order_close' => "合約賣出",
        ],

        'jp' => [
            'store_otc_sell_entrust' => "发布OTC出售广告委托",
            'cancelOtcEntrust' => "撤销OTC委托",
            'confirmOtcOrder' => "OTC订单交易完成",
            'store_otc_order' => "我要出售",
            'cancel_otc_order' => "订单关闭",
            'register_send_stai' => "注册赠送",
            'register_invitation' => "注册邀请奖励",
            'admin_recharge' => "后台充值",
            'recharge' => "コインチャージ",
            'recharge_audit' => "コインチャージ審査です",
            'withdraw' => "コインを引き上げます",
            'cancel_withdraw' => "通貨引き上げ撤回です",
            'withdraw_fee' => "コイン引き出し手数料",
            'reject_withdraw' => "通貨引上げ審査拒否です",
            'fund_transfer' => "資金を回す",
            "bet_option" => "買い入れオプション",
            "bet_option_fee" => "オプション手数料",
            "option_order_delivery" => "オプション受渡し",
            "option_order_cancel" => "オプション註文流局です",
            "store_buy_entrust" => "コイン取引の購入依頼を行います",
            "store_sell_entrust" => "コイン取引の販売依頼を出します",
            "entrust_exchange" => "コインの取引が成立しました",
            "cancel_entrust" => "請求を取り下げます",
            "dividend" => "配当します",
            "subscribe" => "申し込みます",
            "subscribe_activity" => "申し込みキャンペーン贈呈です",
            "open_position" => "先物取引凍結です",
            "open_position_fee" => "先物オープン手数料です",
            "contract_deal" => "先物取引です",
            "close_position" => "先物取引証拠金の放出です",
            "close_position_fee" => "先物取引手数料です",
            "close_long_position" => "先物平価損益計算書",
            "close_short_position" => "先物取引損益計算書",
            "system_flat_position" => "システム強平化です",
            "system_close_position" => "パンク保証金放出です",
            "system_close_position_fee" => "パンク手数料です",
            "system_close_long_position" => "爆倉平多損益決算です",
            "system_close_short_position" => "損益計算書の提出が滞りました",
            "cancel_open_position" => "契約破棄、保証金返還です",
            "cancel_open_position_fee" => "契約破棄,手数料返金です",
            "position_capital_cost" => "先物取引資金料です",
            "buy_pledge_product" => "マイニングの質を買います",
            "sell_pledge_product" => "ロック解除マイニングです",
            "sign_send_stai" => 'サインイン贈呈', // 小白
        ],
        'kor' => [
            'store_otc_sell_entrust' => "发布OTC出售广告委托",
            'cancelOtcEntrust' => "撤销OTC委托",
            'confirmOtcOrder' => "OTC订单交易完成",
            'store_otc_order' => "我要出售",
            'cancel_otc_order' => "订单关闭",
            'register_send_stai' => "注册赠送",
            'register_invitation' => "注册邀请奖励",
            'admin_recharge' => "后台充值",
            'recharge' => "コインチャージ",
            'recharge_audit' => "コインチャージ審査です",
            'withdraw' => "コインを引き上げます",
            'cancel_withdraw' => "通貨引き上げ撤回です",
            'withdraw_fee' => "コイン引き出し手数料",
            'reject_withdraw' => "通貨引上げ審査拒否です",
            'fund_transfer' => "資金を回す",
            "bet_option" => "買い入れオプション",
            "bet_option_fee" => "オプション手数料",
            "option_order_delivery" => "オプション受渡し",
            "option_order_cancel" => "オプション註文流局です",
            "store_buy_entrust" => "コイン取引の購入依頼を行います",
            "store_sell_entrust" => "コイン取引の販売依頼を出します",
            "entrust_exchange" => "コインの取引が成立しました",
            "cancel_entrust" => "請求を取り下げます",
            "dividend" => "配当します",
            "subscribe" => "申し込みます",
            "subscribe_activity" => "申し込みキャンペーン贈呈です",
            "open_position" => "先物取引凍結です",
            "open_position_fee" => "先物オープン手数料です",
            "contract_deal" => "先物取引です",
            "close_position" => "先物取引証拠金の放出です",
            "close_position_fee" => "先物取引手数料です",
            "close_long_position" => "先物平価損益計算書",
            "close_short_position" => "先物取引損益計算書",
            "system_flat_position" => "システム強平化です",
            "system_close_position" => "パンク保証金放出です",
            "system_close_position_fee" => "パンク手数料です",
            "system_close_long_position" => "爆倉平多損益決算です",
            "system_close_short_position" => "損益計算書の提出が滞りました",
            "cancel_open_position" => "契約破棄、保証金返還です",
            "cancel_open_position_fee" => "契約破棄,手数料返金です",
            "position_capital_cost" => "先物取引資金料です",
            "buy_pledge_product" => "マイニングの質を買います",
            "sell_pledge_product" => "ロック解除マイニングです",
            "sign_send_stai" => 'サインイン贈呈', // 小白
        ],
    ];

    public static function getLogTypeText($log_type)
    {
        $lang = App::getLocale();
        return isset(self::$logType[$lang][$log_type]) ? __(self::$logType[$lang][$log_type]) : '';
    }

    public function getLogTypeTextAttribute()
    {
        $lang = App::getLocale();
        return isset(self::$logType[$lang][$this->log_type]) ? __(self::$logType[$lang][$this->log_type]) : '';
    }

    public function getCoinNameAttribute()
    {
        $coin_name = Coins::query()->where('coin_id', $this->coin_id)->value('coin_name');
        return blank($coin_name) ? '' : $coin_name;
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'user_id');
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::createFromTimestamp(strtotime($value))
            ->timezone(config('app.timezone'))
            ->toDateTimeString();
    }

    public function getUpdatedAtAttribute($value)
    {
        return Carbon::createFromTimestamp(strtotime($value))
            ->timezone(config('app.timezone'))
            ->toDateTimeString();
    }

}
